version: '3'
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    command: /go/bin/btcd -u USER -P PASS --rpclisten=0.0.0.0:18556
      --listen=0.0.0.0:18555 --simnet --connect=10.6.0.12:18555
      --connect=10.6.0.13:18555 --connect=10.6.0.14:18555
      --miningaddr=SSwfPFMdZMGvQ5VyBQsHPdy69sPxevhxe5
    cap_add:
      - ALL
    networks:
      vpcbr:
        ipv4_address: 10.6.0.11
  node2:
    build:
      context: .
      dockerfile: Dockerfile
    command: /go/bin/btcd -u USER -P PASS --rpclisten=0.0.0.0:18556
      --listen=0.0.0.0:18555 --simnet --connect=10.6.0.11:18555
      --connect=10.6.0.13:18555 --connect=10.6.0.14:18555
      --miningaddr=SSwfPFMdZMGvQ5VyBQsHPdy69sPxevhxe5
    cap_add:
      - ALL
    networks:
      vpcbr:
        ipv4_address: 10.6.0.12
  node3:
    build:
      context: .
      dockerfile: Dockerfile
    command: /go/bin/btcd -u USER -P PASS --rpclisten=0.0.0.0:18556
      --listen=0.0.0.0:18555 --simnet --connect=10.6.0.12:18555
      --connect=10.6.0.11:18555 --connect=10.6.0.14:18555
      --miningaddr=SSwfPFMdZMGvQ5VyBQsHPdy69sPxevhxe5
    cap_add:
      - ALL
    networks:
      vpcbr:
        ipv4_address: 10.6.0.13
  node4:
    build:
      context: .
      dockerfile: Dockerfile
    command: /go/bin/btcd -u USER -P PASS --rpclisten=0.0.0.0:18556
      --listen=0.0.0.0:18555 --simnet --connect=10.6.0.12:18555
      --connect=10.6.0.13:18555 --connect=10.6.0.11:18555
      --miningaddr=SSwfPFMdZMGvQ5VyBQsHPdy69sPxevhxe5
    cap_add:
      - ALL
    networks:
      vpcbr:
        ipv4_address: 10.6.0.14
#   btcwallet:
#     build: 
#       context: .
#       dockerfile: Dockerfile-btcwallet
#     volumes:
#       - type: bind
#         source: ./btcwallet
#         target: /go/btcwallet
#     command: ["/go/bin/btcwallet", "-C", "/go/btcwallet/sample.conf"]

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
